#!/bin/sh

if [ "$1" = "configure" ]; then
  mkdir -p "/usr/share/deepin/dde-file-manager/oem-menuextensions"
  cp -a "/usr/lib/dde-file-manager-menu-quick-hash-plugin-third-party/hash.desktop" "/usr/share/deepin/dde-file-manager/oem-menuextensions/dde-file-manager-menu-quick-hash-plugin-third-party.desktop"
fi

